---
project_dir: ~/.script
downloads_dir: ~/Downloads

downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes
configure_npm: no
configure_extra: yes
configure_dock: yes

dotfiles_repo: https://github.com/z0ph/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .osx
  - .zsh

homebrew_installed_packages:
  - autoconf
  - automake
  - zsh
  - bash-completion
  - git
  - go
  - gpg
  - nvm
  - ssh-copy-id
  - wget
  - curl
  - htop
  - kubernetes-cli
  - kubernetes-helm
  - mas
  - ncdu
  - lftp
  - vim
  - packer
  - terraform
  - tree
  - dockutil
  - watch
  - calc
  - gnutls
  - unrar
  - aws-shell
  - coreutils
  - libgcrypt
  - openssl
  - ruby
  - awscli
  - nmap
  - python
  - python3
  - awless
  - direnv
  - gnupg
  - node
  - sqlite

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - firefox
  - sublime-text
  - dropbox
  - cyberduck
  - grammarly
  - handbrake
  - teamviewer
  - enpass
  - sequel-pro # MySQL Client (GUI)
  - font-fira-mono-for-powerline
  - font-fira-mono-for-powerline
  - alfred
  - iterm2
  - spotify
  - cleanmymac
  - etcher # flash usb drives
  - tunnelblick # vpn client
  - gitkraken # git with a gui
  - docker-edge # still working?
  - homebrew/cask-versions/docker-edge
  - vlc
  - franz # client whatsapp, telegram, slack, etc.
  - visual-studio-code

npm_global_package:
  - pm2

# See `geerlingguy.mas` role documentation for usage instructions.
mas_signin_dialog: yes
mas_installed_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 1176895641, name: "Spark" }
  - { id: 1039633667, name: "Irvue" }
  - { id: 409183694, name: "Keynote" }
  - { id: 557168941, name: "Tweetbot for Twitter" }
  - { id: 715768417, name: "Microsoft Remote Desktop" }
  - { id: 784801555, name: "Microsoft OneNote" }

mas_upgrade_all_apps: yes

osx_script: "~/.osx --no-restart"

dockitems_disabled:
  - Launchpad
  - Siri
  - Mail
  - Safari
  - Contacts
  - Notes
  - Rappels
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendrier
  - Terminal
  - Plans
  - Pages
  - Numbers
  - Keynote
  - Préférences Système

dockitems_enabled:
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Tweetbot
    path: "/Applications/Tweetbot.app"
    pos: 3
  - name: Telegram
    path: "/Applications/Telegram.app"
    pos: 4
  - name: YakYak
    path: "/Applications/YakYak.app"
    pos: 5
  - name: Franz
    path: "/Applications/Franz.app"
    pos: 6
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 7
  - name: Préférences Système
    path: "/Applications/System Preferences.app"
    pos: 8
