---
- name: Register path to sed.
  command: which sed
  register: sed_which_result
  changed_when: false
  when: sed_path is undefined

- name: Define sed_path variable.
  set_fact:
    sed_path: "{{ sed_which_result.stdout }}"
  when: sed_path is undefined

- name: Copy sudoers configuration into place.
  template:
    src: templates/sudoers.j2
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  become: yes